//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=207.246.73.98,1433;Initial Catalog=ProyectoIntegradorInmogestionPlus;" +
            "User ID=ANGEL;Password=H45i44g40r38@;TrustServerCertificate=True")]
        public string ProyectoIntegradorInmogestionPlusConnectionString {
            get {
                return ((string)(this["ProyectoIntegradorInmogestionPlusConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=207.246.73.98,1433;Initial Catalog=ProyectoIntegradorInmogestionPlus;" +
            "User ID=ANGEL;Password=H45i44g40r38@;Encrypt=True;TrustServerCertificate=True")]
        public string ProyectoIntegradorInmogestionPlusConnectionString1 {
            get {
                return ((string)(this["ProyectoIntegradorInmogestionPlusConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=207.246.73.98;Initial Catalog=ProyectoIntegradorInmogestionPlus;Persi" +
            "st Security Info=True;User ID=Angel;Password=H45i44g40r38@;Encrypt=False")]
        public string ProyectoIntegradorInmogestionPlusConnectionString2 {
            get {
                return ((string)(this["ProyectoIntegradorInmogestionPlusConnectionString2"]));
            }
        }
    }
}
